name: Workflow Template Usage
on: workflow_dispatch
jobs:
  template-usage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Workflow Template
        uses: .github/workflows/template.yml@main
        with:
          sampleTextInput: 'Hello, World!'