name: APIM Configuration Workflow
on:
  workflow_call:
    inputs:
      configPath:
        required: true
        type: string
env:
  PROFILE_FILE_NAME: profile.json
  POLICIES_FILE_NAME: policies.xml
jobs:
  profile:
    name: Applying Profile
    runs-on: ubuntu-latest    
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/development' && 'development' }}
    steps:
      - name: Profile File
        run: echo "${{ inputs.configPath }}/$PROFILE_FILE_NAME"
      # add more steps here
  policies:
    needs: profile
    name: Applying Policies
    runs-on: ubuntu-latest
    steps:
      - name: Profile File
        run: echo "${{ inputs.configPath }}/$PROFILE_FILE_NAME"
      # add more steps here
