name: Workflow Template
on:
  workflow_call:
    inputs:
      sampleTextInput:
        required: true
        type: string
jobs:
  template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Echo Sample Text Input
        run: echo "${{ inputs.sampleTextInput }}"