name: APIM Configuration Workflow
on:
  workflow_call:
    inputs:
      configPath:
        required: true
        type: string
env:
  PROFILE_FILE_NAME: profile.json
  POLICIES_FILE_NAME: policies.xml
jobs:
  template:
    name: APIM Configuration Workflow
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/development' && 'development' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Profile File
        run: echo "${{ inputs.configPath }}/$PROFILE_FILE_NAME"
      - name: Policies File
        run: echo "${{ inputs.configPath }}/$POLICIES_FILE_NAME"
